name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🟢 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.20.0'

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🧪 Executar testes Cypress em modo headless
        run: npx cypress run
